application: flycrosser
version: 1
runtime: python
api_version: 1

handlers:
- url: /common
  static_dir: common

- url: /singlecross
  static_dir: singlecross

- url: /multicross
  static_dir: multicross

- url: /api/singlecross/.*
  script: singlecross.py

- url: /api/multicross/.*
  script: multicross.py

- url: /.*
  script: index.py
